### ISSUE TITLE
uw_memused shows 0%

### ISSUE THREAD

**Issue by shlima** [rderoldan1/usagewatch_ext#6]
uw_memused shows 0% on Ubuntu 15.04 (real ram usage is 30%)

**Comment by rderoldan1** [comment]
I'm going to review this!!

**Comment by rderoldan1** [comment]
Hi @shlima, I had have review this issue, and I found that the original is where the issue lives:
related issue: https://github.com/nethacker/usagewatch/issues/16

I'm reviewing if patch the error directly here, because the original repo I think is not maintained any more.
